### ISSUE TITLE
Importing enum from '@ns'

### ISSUE THREAD

**Issue by Tanimodori** [Tanimodori/viteburner#17]
```ts
import { NS, CrimeType } from '@ns';

export async function main(ns: NS) {
  ns.tprint(CrimeType.shoplift);
}
```

Will result in:

```bash
[viteburner] Error: Failed to resolve import "@ns" from "playground\src\enum\index.ts". Does the file exist?
```

**Comment by Tanimodori** [comment]
Enums in TypeScript is special. It generates codes both on type domain and variable domain. For example, the code

```ts
enum CrimeType {
  shoplift = "Shoplift",
  robStore = "Rob Store",
  mug = "Mug",
  larceny = "Larceny",
  dealDrugs = "Deal Drugs",
  bondForgery = "Bond Forgery",
  traffickArms = "Traffick Arms",
  homicide = "Homicide",
  grandTheftAuto = "Grand Theft Auto",
  kidnap = "Kidnap",
  assassination = "Assassination",
  heist = "Heist",
}
```

... will result in:

```js
"use strict";
var CrimeType;
(function (CrimeType) {
    CrimeType["shoplift"] = "Shoplift";
    CrimeType["robStore"] = "Rob Store";
    CrimeType["mug"] = "Mug";
    CrimeType["larceny"] = "Larceny";
    CrimeType["dealDrugs"] = "Deal Drugs";
    CrimeType["bondForgery"] = "Bond Forgery";
    CrimeType["traffickArms"] = "Traffick Arms";
    CrimeType["homicide"] = "Homicide";
    CrimeType["grandTheftAuto"] = "Grand Theft Auto";
    CrimeType["kidnap"] = "Kidnap";
    CrimeType["assassination"] = "Assassination";
    CrimeType["heist"] = "Heist";
})(CrimeType || (CrimeType = {}));
```

So `CrimeType` needs to exist both in type domain and variable domain. But this is not possible in bitburner as `NetscriptDefinitions.d.ts` is a [declaration file](https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html) which cannot contain variable domain contents. It uses `declare enum CrimeType` to avoid emitting actual code to variable domain.

So the following code will result in compile-time error:

```ts
import { NS, CrimeType } from '@ns';

export async function main(ns: NS) {
  ns.tprint(CrimeType.shoplift);
}
```

As the `CrimeType` from `@ns` (`NetscriptDefinitions.d.ts`) does not exist in variable domain, the compiler found no matching `CrimeType` so such an error is thrown. You can resolve this using `import type`:

```ts
import type { NS, CrimeType } from '@ns';

export async function main(ns: NS) {
  ns.tprint(CrimeType.shoplift); // TS1361
}
```

Now because the `CrimeType` we imported is in type domain only, we cannot use `CrimeType.shoplift` to retrieve the value in variable domain. We can use only raw value `"Shoplift"` only.

**Comment by fluxxdog** [comment]
I see. Design choice by BB. Thanks for clearing that up!

**Comment by Tanimodori** [comment]
> I see. Design choice by BB. Thanks for clearing that up!

Things would have been much easier if BB exports those `enum`s to the client via nsapi, rather than just in the definition file.
